# lightning.pytorch==2.0.0
name: debug-compile
version: version_0

seed_everything: 42
trainer:
  accelerator: gpu
  precision: 16-mixed
  max_epochs: 300
  callbacks:
    # - class_path: LearningRateFinder
    #   init_args:
    #     # attr_name: optimizer.init_args.lr
    #     update_attr: true
    # - class_path: BatchSizeFinder

model:
  net:
    class_path: Cifar10Resnet18
    init_args:
      num_classes: 10

  loss_module:
    class_path: CrossEntropyLoss

  metric_module:
    class_path: Accuracy

data:
  root: data
  batch_size: 128
  val_split: 0.1
  transforms:
    class_path: DefaultTransforms

optimizer:
  class_path: SGD
  init_args:
    lr: 0.1
    momentum: 0.9
    weight_decay: 5e-4

lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    T_max: ${trainer.max_epochs}
# ckpt_path: null
