# lightning.pytorch==2.0.0
name: debug-test-config-rename
version: version_0

seed_everything: 42
trainer:
  precision: bf16
  max_epochs: 100

model:
  model:
    class_path: Cifar10Resnet18
    init_args:
      num_classes: 10

  loss_module:
    class_path: CrossEntropyLoss

  metric_module:
    class_path: Accuracy

data:
  root: data
  batch_size: 64
  val_split: 0.1
  transforms:
    class_path: transforms.default.DefaultTransforms

optimizer:
  class_path: Adam
  init_args:
    lr: 0.1
ckpt_path: null
